version: "3.8"
services:
  code-racer:
    env_file:
      - .env
    build:
      context: .
      target: dev
      args:
        - DOCKER_BUILDKIT=1
    command: [ "air" ]
    volumes:
      - ./:/code-racer
